[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.poetry]
name = "pyside-app-core"
version = "0.3.0"
description = "Framework for PySide6 Applications"
readme = "README.md"
authors = [
    "Leo Covarrubias <leo@leocov.com>"
]
license = "CC BY 4.0"
repository = "https://github.com/leocov-dev/pyside-app-core"
classifiers = [
    "License :: OSI Approved :: GNU General Public License v3 (GPLv3)",
    "Development Status :: 2 - Pre-Alpha",
    "Topic :: Desktop Environment",
    "Programming Language :: Python",
    "Programming Language :: Python :: 3",
    "Typing :: Typed",
    "Intended Audience :: Developers",
    "Topic :: Software Development :: Libraries :: Python Modules",
]
keywords = ["pyside", "pyside6", "frameless", "app", "style"]
include = [
    "resources/icons",
    "resources/templates"
]

[tool.poetry.dependencies]
python = ">=3.10,<3.13"
pyside6 = "6.7.*"
jinja2 = "^3.1.3"

[tool.poetry.group.dev.dependencies]
mypy = "*"
black = "*"
pytest = "*"
pytest_mock = "*"
pre-commit = "*"
import-linter = "2.*"

[tool.poetry.scripts]
pyside-app-core-compile-rcc = "pyside_app_core.resource_generator.__main__:main"

# ------------------------------
# testing
[tool.pytest.ini_options]
pythonpath = ["src"]

# ------------------------------
# linting
[tool.black]

[tool.mypy]
mypy_path = "$MYPY_CONFIG_FILE_DIR/src"
packages = ["pyside_app_core"]
strict = true
implicit_reexport = true

# ------------------------------
# import linter config and rules
[tool.importlinter]
root_packages = [
    "pyside_app_core",
]
include_external_packages = true

[[tool.importlinter.contracts]]
name = "Module Layering"
type = "layers"
layers = [
    "qt",
    "resource_generator",
    "services",
    "utils",
    "errors",
    "log",
    "constants",
    "types",
]
containers = ["pyside_app_core"]
exhaustive = true


[[tool.importlinter.contracts]]
name = "Widget Layering"
type = "layers"
layers = [
    "standard",
    "widgets",
]
containers = ["pyside_app_core.qt"]


# ------------------------------
