name: Continuous Integration
on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main
    tags-ignore:
      - "*"

jobs:
  test:
    name: Unit Tests

    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: [ "3.12" ]

    steps:
      - name: System Dependencies
        run: >-
          sudo apt-get update && 
          sudo apt-get install -y 
          libxcb-xinerama0 
          libxkbcommon-x11-0 
          libgl1-mesa-glx 
          libegl1 
          libopengl0
          libxcb-icccm4 
          libxcb-image0 
          libxcb-keysyms1 
          libxcb-randr0 
          libxcb-render-util0 
          libxcb-xinerama0 
          libxcb-xfixes0 
          x11-utils 

      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install Hatch
        run: pipx install hatch

      - name: Lint Checks
        run: hatch fmt --check

      - name: Unit Tests
        run: hatch test --python ${{ matrix.python-version }}

      - name: Check compile-rcc
        run: hatch run pyside-app-core-compile-rcc --debug examples/toolbar_app

  build:
    name: Build Smoke Test
    needs: [ test ]

    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Python
        uses: actions/setup-python@v5
        with:
          python-version-file: 'pyproject.toml'

      - name: Install Hatch
        run: pipx install hatch

      - name: Check Build
        run: hatch build

      - name: Archive build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: "pyside-app-core"
          path: dist

  # ---------------------
  # only on merge to main
  release-draft:
    name: Create Draft Release
    if: github.ref == 'refs/heads/main'
    needs: [ test, build ]

    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: write
      pull-requests: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Draft Release
        id: release-draft
        uses: release-drafter/release-drafter@v6
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Release Info
        run: echo ${{ steps.release-draft.outputs.id }} - ${{ steps.release-draft.outputs.tag_name }}
