name: Continuous Integration
on:
  pull_request:
  push:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    name: Unit Tests
    steps:
      - name: System Dependencies
        run: >-
          sudo apt-get update && 
          sudo apt-get install -y 
          libxcb-xinerama0 
          libxkbcommon-x11-0 
          libgl1-mesa-glx 
          libegl1 
          libopengl0
          libxcb-icccm4 
          libxcb-image0 
          libxcb-keysyms1 
          libxcb-randr0 
          libxcb-render-util0 
          libxcb-xinerama0 
          libxcb-xfixes0 
          x11-utils 

      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Python
        uses: actions/setup-python@v5
        with:
          python-version-file: 'pyproject.toml'

      - name: Setup Development Env
        run: bin/setup

      - name: Unit Tests
        run: pytest -k test_ tests/unit

  build:
    runs-on: ubuntu-latest
    name: Build Smoke Test
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Python
        uses: actions/setup-python@v5
        with:
          python-version-file: 'pyproject.toml'

      - name: Check Build
        run: poetry build -n