name: Publish
on:
  release:
    types: [ published ]
jobs:
  pypi:
    runs-on: ubuntu-latest
    name: PyPi Publish
    permissions:
      id-token: write
    steps:
      - name: Install Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Dependencies
        run: python3 -m pip install -U twine

      - name: Download Release Assets
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: gh release download ${{ github.event.release.tag_name }} --dir dist

      - name: Validate Dist Files
        run: twine check dist/**

      - name: Publish To Test Env
        uses: pypa/gh-action-pypi-publish@v1.8.6
        with:
          repository-url: https://test.pypi.org/legacy/